<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>1698960c-c06a-4329-8165-9d752e85cd4b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.5.4-preview.1.26464.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AwesomeApi\AwesomeApi.csproj" />
    <ProjectReference Include="..\..\AwesomeWeb\AwesomeWeb.csproj" />
  </ItemGroup>

</Project>
